# Generated by Django 4.1.2 on 2022-10-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='foodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=25)),
                ('quantity', models.IntegerField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='tv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_size', models.CharField(choices=[(32, "32''"), (43, "43''"), (55, "55''"), (65, "65''"), (75, "75''"), (85, "85''")], max_length=25)),
                ('quantity', models.IntegerField(max_length=25)),
            ],
        ),
    ]
