# Generated by Django 4.1.2 on 2022-10-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tv',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
